### ISSUE TITLE
Tweegeemee stopped breeding

### ISSUE THREAD

**Issue by rogerallen** [rogerallen/tweegeemee#22]
Well, this is strange...I only just noticed that since Feb 4 @tweegeemee has posted random images, never bred children.  From logs it isn't immediately obvious what is up, so I'll have to do some debugging to figure this out.

```
2021-02-06T19:31:42.940351+00:00 app[scheduler.7245]: Caused by: java.lang.IndexOutOfBoundsException
2021-02-06T19:31:42.940411+00:00 app[scheduler.7245]: at clojure.lang.RT.nthFrom(RT.java:924)         2021-02-06T19:31:42.940463+00:00 app[scheduler.7245]: at clojure.lang.RT.nth(RT.java:893)             2021-02-06T19:31:42.940518+00:00 app[scheduler.7245]: at clojure.core$rand_nth.invokeStatic(core.clj:7238)
2021-02-06T19:31:42.940568+00:00 app[scheduler.7245]: at clojure.core$rand_nth.invoke(core.clj:7231)
2021-02-06T19:31:42.940621+00:00 app[scheduler.7245]: at tweegeemee.core$post_children_to_web.invokeStatic(core.clj:249)
2021-02-06T19:31:42.940674+00:00 app[scheduler.7245]: at tweegeemee.core$post_children_to_web.invoke(core.clj:243)
2021-02-06T19:31:42.940727+00:00 app[scheduler.7245]: at tweegeemee.core$_main.invokeStatic(core.clj:292)
2021-02-06T19:31:42.940778+00:00 app[scheduler.7245]: at tweegeemee.core$_main.doInvoke(core.clj:285)
2021-02-06T19:31:42.940829+00:00 app[scheduler.7245]: at clojure.lang.RestFn.invoke(RestFn.java:397)
2021-02-06T19:31:42.940869+00:00 app[scheduler.7245]: at clojure.lang.Var.invoke(Var.java:380)        2021-02-06T19:31:42.940930+00:00 app[scheduler.7245]: at user$eval140.invokeStatic(form-init7273698243033875180.clj:1)
2021-02-06T19:31:42.940982+00:00 app[scheduler.7245]: at user$eval140.invoke(form-init7273698243033875180.clj:1)
2021-02-06T19:31:42.941036+00:00 app[scheduler.7245]: at clojure.lang.Compiler.eval(Compiler.java:7176)
2021-02-06T19:31:42.941093+00:00 app[scheduler.7245]: at clojure.lang.Compiler.eval(Compiler.java:7166)
2021-02-06T19:31:42.941147+00:00 app[scheduler.7245]: at clojure.lang.Compiler.load(Compiler.java:7635)
2021-02-06T19:31:42.941236+00:00 app[scheduler.7245]: ... 12 more 
```

**Comment by rogerallen** [comment]
Trying to get some statuses with the tweegeemee auth gives:
```
clj꞉tweegeemee.explore꞉>   (tw/statuses-user-timeline
   :oauth-creds @tgm/my-twitter-creds
   :params {:count 1
            :screen-name @tgm/my-screen-name})
; Execution error at jdk.internal.reflect.NativeConstructorAccessorImpl/newInstance0 (NativeConstructorAccessorImpl.java:-2).
; Twitter responded to request with error 32: Could not authenticate you.
```

- trying a python api with tweegeemee auth works
- revoking & regenerating tokens didn't make anything better
- using my "test" developer "roger__allen" works fine for the above test, though.  Hmm...

**Comment by rogerallen** [comment]
Earlier issue with authentication was configuration problem with secrets env file.  Using USER_ACCESS_SECRET and not USER_ACCESS_TOKEN_SECRET now.  Older config file hadn't been updated.
